#!/bin/sh

if [ -n "/opt/serieswatcher/lib" ]; then
   if [ "${LD_LIBRARY_PATH+set}" = "set" ]; then
       export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/serieswatcher/lib"
   else
       export LD_LIBRARY_PATH="/opt/serieswatcher/lib"
   fi
fi
exec /opt/serieswatcher/bin/serieswatcher "$@"
